# Generated by Django 3.0.3 on 2022-01-17 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211119_1448'),
        ('users', '0002_remove_customuser_phonenumber'),
    ]

    operations = [
    ]
