# Generated by Django 3.0.3 on 2022-01-23 07:56

from django.db import migrations, models
import drivers.models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_auto_20220118_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverprofilemodel',
            name='profile_photo',
            field=models.ImageField(null=True, upload_to=drivers.models.photo_upload),
        ),
    ]
