# Generated by Django 3.2.9 on 2021-11-19 11:54

from django.db import migrations, models
import django.db.models.deletion
import shops.models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_auto_20211119_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addonmodel',
            name='added_price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='addonmodel',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='add_ons', to='shops.productmodel'),
        ),
        migrations.AlterField(
            model_name='addonmodel',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='optiongroupmodel',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='option_groups', to='shops.productmodel'),
        ),
        migrations.AlterField(
            model_name='optiongroupmodel',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='optionmodel',
            name='option_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='shops.optiongroupmodel'),
        ),
        migrations.AlterField(
            model_name='optionmodel',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='photo',
            field=models.ImageField(null=True, upload_to=shops.models.product_photo_upload),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shops.shopprofilemodel'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='slug',
            field=models.SlugField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productreviewmodel',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='shops.productmodel'),
        ),
        migrations.AlterField(
            model_name='productreviewmodel',
            name='sort',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='productreviewmodel',
            name='text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='relyon',
            name='choosed_option_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shops.optiongroupmodel'),
        ),
        migrations.AlterField(
            model_name='relyon',
            name='option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shops.optionmodel'),
        ),
        migrations.AlterField(
            model_name='relyon',
            name='option_group',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rely_on', to='shops.optiongroupmodel'),
        ),
        migrations.AlterField(
            model_name='shopaddressmodel',
            name='area',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shopaddressmodel',
            name='building',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shopaddressmodel',
            name='shop',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address', to='shops.shopprofilemodel'),
        ),
        migrations.AlterField(
            model_name='shopaddressmodel',
            name='street',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shopreviewmodel',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='shops.shopprofilemodel'),
        ),
        migrations.AlterField(
            model_name='shopreviewmodel',
            name='sort',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
